Show avatar placeholder in settings
mozilla-mobile/mozilla-vpn-client pull request #1406
Opened 2021-07-22 18:30 UTC by flozia

This PR adds a placeholder to the settings view that is displayed until the user avatar is successfully loaded.

**Screenshots**
![Uploading settings-avatar-placeholder.png…]()

Resolves #552

2021-08-16 13:34 UTC, bakulf commented
Can you rebase this PR? If @lesleyjanenorton is happy with it, I would like to see it merged in 2.5.

2021-08-16 14:29 UTC, lesleyjanenorton commented
@bakulf almost! I will finish reviewing this today.

2021-08-17 03:00 UTC, lesleyjanenorton requested changes

2021-08-18 15:01 UTC, flozia commented on src/ui/components/VPNPanel.qml
> +            VPNAvatar {
`VPNAvatar` is now only visible in the Settings view and the mentioned issues should be fixed. @lesleyjanenorton

2021-08-18 21:02 UTC, lesleyjanenorton approved these changes
Woohoo! looks great - thank you @flozia ! 🤩
<img width="363" alt="Screen Shot 2021-08-18 at 3 38 32 PM" src="https://user-images.githubusercontent.com/22355127/129971716-6ab4ba77-b2ca-4cc7-a67c-26163758517b.png">

2021-08-18 21:02 UTC, merged