Block all unallowed dns traffic
mozilla-mobile/mozilla-vpn-client pull request #1566
Opened 2021-08-17 14:55 UTC by strseb

we block all non-tunnel traffic with the killswitch but any dns server reachable through the tunnel may still be used. Lets block all dns traffic unless it's targeted to our dns server from the config. 

closes #1546

2021-08-17 21:31 UTC, oskirby requested changes
Looks good, but I would appreciate it if you could address the linter warnings first.

2021-08-17 21:31 UTC, oskirby commented on src/platforms/windows/daemon/windowsfirewall.cpp
> +  conds[1].conditionValue.uint16 = (IPPROTO_TCP);
If the type is `FWP_UINT8` then this should be `conds[1].conditionValue.uint8 = (IPPROTO_TCP)`

2021-08-18 19:43 UTC, bakulf approved these changes

2021-08-18 20:13 UTC, oskirby approved these changes

2021-08-18 20:28 UTC, merged