implement in app support client side with additions to featurelist
mozilla-mobile/mozilla-vpn-client pull request #1584
Opened 2021-08-19 07:18 UTC by mbirghan

This PR implements:
- the frontend of the in app support flow
- creating a support ticket on guardian
- an addition to `FeatureList` to load a feature list (unauthSupportEnabled in this case) from guardian
- enable the unauthenticated in app support form if enabled

2021-08-19 12:03 UTC, bakulf requested changes
Good! Some minor things. Thanks!

2021-08-19 12:03 UTC, bakulf commented on src/ui/views/ViewContactUs.qml
> +                                //% "Email address"
Use the validation method in the haserror property.

2021-08-19 12:03 UTC, bakulf commented on src/ui/views/ViewContactUs.qml
> +                            placeholderText: qsTrId("vpn.contactUs.confirmEmailAddress")
Same here plus email comparison

2021-08-19 15:46 UTC, mbirghan commented on src/ui/main.qml
> +            mainStackView.push("views/ViewContactUs.qml");
Yea I check it and it works as expected.

2021-08-19 15:48 UTC, mbirghan commented on src/featurelist.cpp
> +  return m_unauthSupportSupported;
Since we send a request at startup we should always be up to date but I can also cache it in settings.

2021-08-19 16:39 UTC, mbirghan commented on src/inspector/inspectorwebsocketconnection.cpp
> +
If we do not find the feature we pint out a list with all the available features as an error message.

2021-08-19 16:39 UTC, mbirghan commented on src/inspector/inspectorwebsocketconnection.cpp
> +
If you enter a wrong feature we print out all the available features.

2021-08-19 17:33 UTC, bakulf approved these changes

2021-08-19 17:33 UTC, bakulf commented on src/featurelist.cpp
> +  return m_unauthSupportSupported;
ok!

2021-08-20 12:09 UTC, bakulf commented on src/featurelist.h
remove this empty line

2021-08-20 15:23 UTC, merged