Don't use Unicode character in alerts on Android
mozilla-mobile/mozilla-vpn-client pull request #1792
Opened 2021-09-10 02:17 UTC by lesleyjanenorton

2021-09-10 03:10 UTC, oskirby commented
Maybe this is a silly question, but why are we using unicode at all for this? Surely a good old fashion ASCII space should do the job?

2021-09-10 06:02 UTC, bakulf approved these changes

2021-09-10 06:05 UTC, bakulf requested changes

2021-09-10 06:05 UTC, bakulf commented on src/ui/components/VPNAlert.qml
> +                property var whiteSpaceCharacter: Qt.platform.os === "windows" || Qt.platform.os === "android" ? " " : "\u0001"
Why do we want to use 0001? That is a control simbol and not a whitespace.

2021-09-10 14:39 UTC, lesleyjanenorton commented
@oskirby you would think but for whatever reason it doesn't work on apple devices

2021-09-10 15:53 UTC, lesleyjanenorton commented
@oskirby It does the job everywhere except the update banner on Apple devices. 
<img width="747" alt="Screen Shot 2021-09-10 at 10 17 45 AM" src="https://user-images.githubusercontent.com/22355127/132881742-de0f0020-36b4-44ee-b193-b7083ba665ea.png">
<img width="773" alt="Screen Shot 2021-09-10 at 10 17 33 AM" src="https://user-images.githubusercontent.com/22355127/132882006-a5677542-40ff-4aec-8194-66ae5d1be6fc.png">

2021-09-13 14:58 UTC, bakulf approved these changes

2021-09-13 14:58 UTC, merged