Use Constants::API Staging as default value if none is given
mozilla-mobile/mozilla-vpn-client pull request #1843
Opened 2021-09-20 12:06 UTC by strseb

We should use Constants::API_STAGING_URL as Default setting value if MVPN_API_BASE_URL is not present - Otherwise auth uri might be empty and stuck on windows (and we crash on android) ... also I don't want to copy our guardian uri every time I install a debug build on my phone :) 🙈

2021-09-20 12:26 UTC, bakulf commented
I would like to hide the 'staging' env. What about if we use the prod URL by default? And we remove API_STAGING_URL entirely?

2021-09-20 13:02 UTC, strseb commented
Sure :)

2021-09-20 13:05 UTC, bakulf approved these changes

2021-09-20 13:25 UTC, mbirghan requested changes

2021-09-20 13:25 UTC, mbirghan commented on src/settingsholder.h
>    QString getEnvVariable(const QString& name) const;
This can be removed.

2021-09-20 13:25 UTC, mbirghan commented on src/constants.h
> -    "https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net";
We still use this in two places. We should remove it there too.
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/platforms/wasm/wasmnetworkrequest.cpp#L59
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/tests/unit/mocnetworkrequest.cpp#L40

2021-09-21 07:11 UTC, mbirghan approved these changes

2021-09-21 12:48 UTC, merged