Pin Device Key Registration To <2.5
mozilla-mobile/mozilla-vpn-client pull request #2767
Opened 2022-02-15 18:49 UTC by strseb

So 2 Things go wrong here: 

We're refreshing the device key on any update, even though we only need to to it when a key has been used before the 2.5 update. 

Also looking at the video at: 0:51-0:57. 
- After refresh  we also scheudle a full account refresh, pulling in the new devices
- We can see on the video the device count now dropped from 5 to 4
- It's likely that the devicemodel no longer includes the current keys. 
- YSo we should check on activation this is the case. 
https://mozilla-hub.atlassian.net/browse/VPN-1747

2022-02-15 19:34 UTC, bakulf requested changes

2022-02-15 19:34 UTC, bakulf commented on src/controller.cpp
> +  if (device == nullptr) {
how can it be we are here? Can you tell me more?

2022-02-16 10:56 UTC, bakulf commented
>     * After refresh  we also scheudle a full account refresh, pulling in the new devices

Right.

>     * I think the update of the device failed, and thus guardian has removed it. (idk why tho)

This is now shown in the log. In the log we see a full activation after the device key re-generation.

> Maybe we should force a full reset() of the app here, so the user can-re login and reauth the device.

Good point. Follow up?
Let's change this PR to stop the key regeneration at each update.

2022-02-16 13:35 UTC, strseb commented
Followup for the controllerstuff is here https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2776

2022-02-16 13:51 UTC, bakulf approved these changes

2022-02-16 14:09 UTC, bakulf commented
I merge this and I cherry-pick it to 2.7.1 too

2022-02-16 14:11 UTC, merged