Discard data on download progress
mozilla-mobile/mozilla-vpn-client pull request #2988
Opened 2022-03-12 16:44 UTC by flozia

2022-03-12 16:48 UTC, flozia commented on src/networkrequest.cpp
> +              m_reply->readAll();
If I’m understanding correctly this would prevent us from storing downloaded data in memory. Is this a feasible approach?

2022-03-12 16:48 UTC, flozia commented on src/networkrequest.cpp
> +              m_reply->readAll();
If I’m understanding correctly this would prevent us from storing downloaded data in memory. Is this a feasible approach?

2022-03-12 21:37 UTC, bakulf requested changes
I like this solution but i think we can simplify it a lot. What about if we introduce a new signal as you did, but passing the network relay object together with the bytes received and total. The slot, in the benchmark class, can call readAll().

Would it work?

2022-03-13 07:38 UTC, bakulf commented
Or even better you can use `sender()->replay()`

2022-03-13 14:23 UTC, flozia commented
> I like this solution but i think we can simplify it a lot. What about if we introduce a new signal as you did, but passing the network relay object together with the bytes received and total. The slot, in the benchmark class, can call readAll().
> 
> Would it work?

That works and is a lot cleaner — yes! I wasn’t sure how to get it working with `sender()->replay()` though.

2022-03-13 19:51 UTC, bakulf requested changes

2022-03-13 19:51 UTC, bakulf commented on src/connectionbenchmark/benchmarktaskdownload.cpp
> +    m_bytesReceived = bytesReceived;
Don't you have to sum these 2 values?

2022-03-14 10:40 UTC, bakulf approved these changes

2022-03-14 15:04 UTC, flozia commented on src/connectionbenchmark/benchmarktaskdownload.cpp
> +  reply->readAll();
Done.

2022-03-14 16:08 UTC, merged