Always reset profile flow before starting it
mozilla-mobile/mozilla-vpn-client pull request #3821
Opened 2022-06-22 17:45 UTC by flozia

## Description

Make sure to always reset the profile flow.

## Reference

[VPN-2436](https://mozilla-hub.atlassian.net/browse/VPN-2436)

## Checklist
    
- [x] My code follows the style guidelines for this project
- [x] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [x] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2022-06-22 17:49 UTC, strseb approved these changes

2022-06-22 18:14 UTC, bakulf approved these changes

2022-06-22 18:15 UTC, bakulf requested changes

2022-06-22 18:15 UTC, bakulf commented on src/ui/settings/ViewSettingsMenu.qml
> +                        VPNProfileFlow.reset();
call `reset` in `start`

2022-06-24 05:40 UTC, bakulf requested changes
We discuss this on slack. Request changes.

2022-06-24 10:55 UTC, closed without merging