temp skip flaky test and fix testsubscription data
mozilla-mobile/mozilla-vpn-client pull request #4776
Opened 2022-11-01 13:15 UTC by mozrokafor

## Description

    temp skip flaky steps in multihop and fix testsubscription data

## Reference

    [JIRA TICKET](https://mozilla-hub.atlassian.net/browse/PSP-557)

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2022-11-01 14:11 UTC, strseb approved these changes

2022-11-01 16:30 UTC, bakulf requested changes

2022-11-01 16:30 UTC, bakulf commented on tests/functional/testMultihop.js
> +  it.skip('check the countries and cities for multihop entries', async () => {
why?

2022-11-01 16:30 UTC, bakulf commented on tests/functional/testMultihop.js
> +      for (let city of server.cities) {
remove these extra spaces.

2022-11-01 16:30 UTC, bakulf commented on tests/functional/testMultihop.js
> +  it.skip('Server switching -- different country different cities', async () => {
why?

2022-11-01 16:30 UTC, bakulf commented on tests/functional/testMultihop.js
> +  it.skip('Single and multihop switching', async () => {
why?

2022-11-01 16:30 UTC, bakulf commented on tests/functional/testSubscription.js
> +            activated: '10/1/70',
can you tell me why these changes?

2022-11-08 01:18 UTC, mozrokafor commented
fixed - https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4827, https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4840

2022-11-08 01:18 UTC, closed without merging