Vpn 3071(Part 1) Split products
mozilla-mobile/mozilla-vpn-client pull request #4839
Opened 2022-11-06 05:50 UTC by birdsarah

## Description

    Split products management out of IAPHandler. This paves the way for more purchase management in app on desktop.

## Reference

    VPN-3071

## Checklist
    
- [x] My code follows the style guidelines for this project
- [x] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2022-11-08 15:06 UTC, bakulf requested changes
I don't understand why we have IAPHandler and ProductHandler. We can have 1 single class for both?

2022-11-09 00:18 UTC, birdsarah commented
@bakulf re-requesting review.

I fixed the comment comment but not your other two notes.

To recap what we discussed earlier:

* Splitting the IAPHandler into IAPHandler and ProductsHandler paves the way for the next PR where I will create PurchaseHandler with subclasses PurchaseIAPHandler and PurchaseWebHandler. Because PurchaseWebHandler has no product handling dependencies this makes this hierarchy clean.
* What is not clean is that I'm short on time and instead of splitting the native implementations (wasmiaphandler, iosiaphandler, and androidiaphandler) into two pieces also I've left them together. I've done this for expediency for delivering this feature by Monday. It's not as clean as it could be. I can pick this clean-up work up for 2.13.
* Also, for posterity, to recap our conversation that my initial preference for implementing this was PurchaseHandler (QObject) has subclasses PurchaseIAPHandler and PurchaseWebHandler where the PurchaseIAPHandler multi-inherited from PurchaseHandler and QAbastractList so that PurchaseIAPHandler could be the model for the QML view. However, Qt does not allow multiple inheritance of two QObjects (QAbstractList is derived from QObject) so this wasn't an option and this is how I ended up with what's in this PR.

2022-11-09 03:40 UTC, birdsarah commented
For reference @bakulf the follow-on PR is here: #4883

The code isn't finished, but the re-org (so you can see the shape of the final product), is mostly done.

2022-11-09 15:04 UTC, bakulf approved these changes

2022-11-10 00:17 UTC, merged