VPN-3473 - Turn on sortincludes on clang-format
mozilla-mobile/mozilla-vpn-client pull request #5163
Opened 2022-12-08 11:10 UTC by brizental

2022-12-08 11:16 UTC, brizental commented on .clang-format
> +SortIncludes: true
This is the change. All the rest is just applying the change.

2022-12-08 12:10 UTC, strseb commented
On windows we have quite a few where the order of imports is important - the the build errors :)

2022-12-08 12:10 UTC, bakulf commented
can you fix the linter? I think we can land this PR.

2022-12-08 13:32 UTC, bakulf requested changes

2022-12-08 13:32 UTC, bakulf commented on src/hacl-star/kremlin/minimal/FStar_UInt128.h
> +
revert these changes. half folder should not be included in clang-format.

2022-12-08 13:46 UTC, brizental commented
> On windows we have quite a few where the order of imports is important - see the build errors :)

Thanks @strseb , it's possible to disable that only for `src/platform/windows` files. Would that be enough?

2022-12-08 14:15 UTC, brizental commented
Oops, closed by mistake.

2022-12-08 14:40 UTC, strseb approved these changes
> Thanks @strseb , it's possible to disable that only for src/platform/windows files. Would that be enough?

yes. :)

2022-12-09 07:06 UTC, bakulf commented
> > Thanks @strseb , it's possible to disable that only for src/platform/windows files. Would that be enough?
> 
> yes. :)

I think it's better to disable the sorting just on specific files via clang-format comments.

2022-12-12 16:05 UTC, birdsarah approved these changes

2022-12-12 18:16 UTC, Gela approved these changes

2022-12-13 16:10 UTC, merged