Support Apple universal builds
mozilla-mobile/mozilla-vpn-client pull request #5199
Opened 2022-12-13 04:23 UTC by oskirby

## Description
Compiled targets for Apple devices don't always have a single architecture that they may need to build for. For example MacOS universal binaries will include symbols for both `aarch64` and `x86_64` within a single binary, and iOS projects may need to build libraries for `x86_64` during simulation and `aarch64` for real devices.

For the most part, Qt and CMake has already sorted this out for us, but our custom cmake helpers to bring in Rust and Golang libraries doesn't support building of universaly binaries. This PR attempts to add that support back in by adding some rust and golang helpers.

## Reference
Github: #286 ([VPN-82](https://mozilla-hub.atlassian.net/browse/VPN-82))

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2022-12-19 10:25 UTC, brizental commented
Removing myself from the reviewers list as I don't feel qualified to review cmake changes. I looked at them, nothing popped out to me and I learned some new stuff. Thanks for implementing this Owen :) I noticed the Jira ticket has not been added to the December sprint. I think we are expected to do that to all bugs we work on during a sprint.

2022-12-20 17:09 UTC, mcleinman requested changes
Getting some errors when building for macOS:
```
error[E0560]: struct `Configuration` has no field named `trim_data_to_registered_pings`
  --> src/lib.rs:42:9
   |
42 |         trim_data_to_registered_pings: false,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Configuration` does not have this field
   |
   = note: available fields are: `upload_enabled`, `data_path`, `application_id`, `max_events`, `delay_ping_lifetime_io` ... and 3 others

error[E0560]: struct `Configuration` has no field named `trim_data_to_registered_pings`
  --> src/lib.rs:79:9
   |
79 |         trim_data_to_registered_pings: false,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Configuration` does not have this field
   |
   = note: available fields are: `upload_enabled`, `data_path`, `application_id`, `max_events`, `delay_ping_lifetime_io` ... and 3 others

For more information about this error, try `rustc --explain E0560`.
error: could not compile `vpnglean` due to 2 previous errors
```
Happy to debug w/ you in real time if you'd like.

2022-12-20 17:54 UTC, brizental commented
@mcleinman You need to update the gid submodule. That is the source of your errors :)

2022-12-21 01:56 UTC, oskirby commented on README.md
> +   will run on both Intel and Apple silicon devices (experimental).
For MacOS, I believe this works on version 6.2.x as well. It's only iOS that requires something newer.

2022-12-22 18:16 UTC, bakulf approved these changes

2022-12-22 22:53 UTC, mcleinman approved these changes
👍🏻 
Cmake is not my specialty, but nothing leaps out at me as off here, and I can successfully get it to build for iOS and macOS. Thanks!

2022-12-22 22:54 UTC, merged