Reset controller on failure
mozilla-mobile/mozilla-vpn-client pull request #520
Opened 2021-01-28 16:23 UTC by strseb

Nothing fancy actually. I realized that `m_controller.initialize();` actually already does all the magic we need. The rest ist just calling this on the backend-error and fix failures that happen on android if we do that actually 🙈

2021-01-29 07:51 UTC, bakulf requested changes

2021-01-29 07:51 UTC, bakulf commented on src/controller.cpp
> +  m_impl.reset(nullptr);
Why is this needed?

2021-01-29 07:51 UTC, bakulf commented on src/platforms/android/androidcontroller.cpp
> +#include "errorhandler.h"
alphabetic order

2021-01-29 07:51 UTC, bakulf commented on src/mozillavpn.cpp
> +        m_private->m_controller.initialize();
OK, but what about all the other controller implementations?
We need to see if all of them work when calling initialize() again.

2021-11-14 20:57 UTC, birdsarah commented
@strseb - close this?

2021-11-15 13:35 UTC, closed without merging