WIP - Start replacing wghelper script
mozilla-mobile/mozilla-vpn-client pull request #546
Opened 2021-02-04 21:17 UTC by birdsarah

WIP to replace wghelper script - or start the process.

2021-02-04 21:40 UTC, bakulf requested changes
In general, I like this approach, but I have a comment to make. If we want to write this code, thinking in a cross-platform way, we can say that each platform has a set of tasks to complete:

1. bring up the interface
2. configure the routing
3. configure the DNS

And, of course, during the shutdown, the opposite tasks. So, I wonder if we can continue in this way, and then generalize it. Similarly to what we have done for the 'Daemon' class. For instance, MacOS has the same operations to complete (with different commands because darwin is a BSD and not a Linux OS, but the tasks are the same).

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/wghelper.cpp
> +  char* wg_devices_raw = wg_list_device_names();
use `wg_for_each_device_name`. It's part of the embedded lib.

What about something like this:

```
char* deviceNames = wg_list_device_names();
size_t len = 0;
QStringList devices;
wg_for_each_device_name(deviceNames, deviceName, len) {
  devices.append(deviceName);
 }
free(deviceNames);
return devices;
```

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/wghelper.cpp
> +  return wg_devices;
you need to call `free(wg_devices_raw);` otherwise, you leak the strings.

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/wghelper.cpp
> +QStringList WireguardHelper::current_wireguard_devices() {
1. Add a `// static` to know it's a static method.
2. currentWireguardDevices()

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/dbusservice.cpp
> +WireguardHelper wg_helper;
This class contains only static methods. You don't  need `wg_helper`. When you need to call a method, just do: `WireguardHelper::name_of_the_method()`

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/dbusservice.cpp
> +  logger.log() << "Interface exists:" << wg_helper.interface_exists();
`WireguardHelper::interfaceExists()`

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/wghelper.cpp
> +bool WireguardHelper::interface_exists() {
We are following the QT C++ style (which is the firefox one too). Call the method: `interfaceExists()`

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/wghelper.cpp
> +  QStringList wg_devices = WireguardHelper::current_wireguard_devices();
Also the variables :) -> wgDevices - or simply `devices`

2021-02-04 21:40 UTC, bakulf commented on src/platforms/linux/daemon/wghelper.h
> +  static bool add_if();
This doesn't exist yet, right?

2021-02-05 01:53 UTC, birdsarah commented
@bakulf - this is a WIP PR. It's me pushing things and having a record of them so I can ask you questions when I need to. I'm not in anyway proposing that this is the final code or code structure. I'm just trying to make progress.

2021-02-05 01:53 UTC, birdsarah commented
https://git.zx2c4.com/wireguard-tools/tree/src/config.c

2021-02-05 02:03 UTC, closed without merging

2021-02-05 02:04 UTC, birdsarah commented
> @bakulf - this is a WIP PR. It's me pushing things and having a record of them so I can ask you questions when I need to. I'm not in anyway proposing that this is the final code or code structure. I'm just trying to make progress.

Apologies if WIP PRs are not the way of doing things in this repo. I should have checked to avoid confusion and time wasting.