ci: use the proper beetmover destination on 'ship-client' phase
mozilla-mobile/mozilla-vpn-client pull request #5844
Opened 2023-02-01 20:00 UTC by ahal

Previously this was pointing at the candidates dir, even when running the ship-client phase.

## Description

    This change fixes the wrong build dirs being linked in the `release-notify` message that gets posted to Slack.

## Checklist
    
- [ x ] My code follows the style guidelines for this project
- [ x ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ x ] I have performed a self review of my own code
- [ x ] I have commented my code PARTICULARLY in hard to understand areas
- [ x ] I have added thorough tests where needed

2023-02-03 21:23 UTC, gabrielBusta approved these changes

2023-02-03 21:26 UTC, gabrielBusta requested changes
The code is assuming a destination path here https://github.com/mozilla-mobile/mozilla-vpn-client/blob/d72b1c3f86f27302d25461df0f34701398c2fbed/taskcluster/mozillavpn_taskgraph/transforms/beetmover.py#L148-L149

2023-02-07 14:09 UTC, ahal commented
Thanks! I think I'd prefer to be explicit, so I added a better exception if we fall off the end of the if statement.

2023-04-03 21:19 UTC, birdsarah commented
Per decision in Feb retro, closing as more than 2 weeks without activity. You can re-open whenever.

2023-04-04 14:27 UTC, gabrielBusta approved these changes

2023-04-05 02:52 UTC, merged