Fix cmake-race with sentry
mozilla-mobile/mozilla-vpn-client pull request #5875
Opened 2023-02-06 12:08 UTC by strseb

## Description

    Describe your changes

## Reference

    i.e Jira or Github issue URL

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2023-02-06 12:39 UTC, brizental approved these changes

2023-02-06 12:48 UTC, bakulf approved these changes

2023-02-06 18:49 UTC, oskirby requested changes
IIRC, the `-buildvcs` flag is only supported on go 1.18 and newer, and this breaks our Ubuntu Focal and Bionic builds which are stuck with go 1.16.

2023-02-06 22:50 UTC, oskirby commented
Actually, it seems that `golang-1.18` packages exist for both [focal-updates](https://packages.ubuntu.com/focal-updates/golang-1.18) and [bionic-updates](https://packages.ubuntu.com/bionic-updates/golang-1.18) so we could probably figure out a way to get Linux building again with go 1.18

2023-02-07 14:47 UTC, oskirby approved these changes

2023-02-07 15:18 UTC, merged