VPN-3896 - network requests coverage for support tickets
mozilla-mobile/mozilla-vpn-client pull request #6175
Opened 2023-02-27 17:46 UTC by mozrokafor

## Description

  network requests coverage for support tickets

## Reference

    [VPN-3896](https://mozilla-hub.atlassian.net/browse/VPN-3896)

2023-03-04 21:25 UTC, bakulf requested changes
Good! Still a few things to improve. But the approach is really good.

2023-03-04 21:25 UTC, bakulf commented on nebula/ui/components/forms/VPNComboBox.qml
> +        objectName: "category-Dropdown-Option-" + index
This cannot be called category because it's a shared component. Maybe it should use the root obj name?

2023-03-04 21:25 UTC, bakulf commented on tests/functional/testContactUs.js
> +    await vpn.wait();
No needed

2023-03-04 21:25 UTC, bakulf commented on tests/functional/testContactUs.js
> +        await vpn.getQueryProperty("//category-Dropdown-Option-4-text", "text"),
Maybe move it to a function? This is dup code

2023-03-04 21:25 UTC, bakulf commented on tests/functional/testContactUs.js
> +      "/api/v1/vpn/createSupportTicket": {
Probably not needed

2023-04-05 03:55 UTC, bakulf requested changes
Great! Can we also test the page shown after the submit?

2023-04-05 03:55 UTC, bakulf commented on tests/functional/servers/guardian_endpoints.js
> +const supportTicketData = {
Where do you use this?

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +    await vpn.wait();
Remove this and check for the loader readiness

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +    await vpn.waitForQueryAndClick(queries.screenSettings.GET_HELP.visible());
After this, check for the loader readiness

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +  await vpn.wait();
Remove this

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +  await vpn.waitForQueryAndClick(queries.screenGetHelp.SUPPORT.visible());
Check the state of the stack view before this line

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +    await openContactUsInSettings(false);
Maybe this function should be renamed. We are not in settings

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +      queries.screenGetHelp.contactSupportView.CONFIRM_EMAIL_INPUTS.visible(),
Check what happens if the 2 inputs do not match

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +    await vpn.waitForQueryAndClick(queries.screenGetHelp.contactSupportView.SUBMIT_BUTTON.visible());
Check the final page?

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +    await vpn.wait();
Remove ;)

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +    await vpn.wait();
Remove them all

2023-04-05 03:55 UTC, bakulf commented on tests/functional/testContactUs.js
> +    it('Email inputs are visible to unauthenticated user', async () => {
Why 2 nested it()?

2023-05-21 23:01 UTC, birdsarah commented on tests/functional/testContactUs.js
> +describe('Authenticated failures', function () {
We have decided to remove the authenticated support form path (https://mozilla-hub.atlassian.net/browse/VPN-3747) so we may be able to get rid of these tests. But we do still want to test that support forms work for both authenticated and unauthenticated users.

2023-06-22 02:13 UTC, lesleyjanenorton commented
Closing for staleness. Feel free to reopen when there is additional work to commit.

2023-06-22 02:13 UTC, closed without merging