Carousel updates
mozilla-mobile/mozilla-vpn-client pull request #6229
Opened 2023-03-06 22:51 UTC by lesleyjanenorton

## Description

- Updates the pre-signup carousel strings (VPN-3307)
- Adjusts the overall height of the app (VPN-4262 - an ask that originates in the first PR for this where the length of the strings created vertical congestion)
- Fixes carousel layout (product ask from review - no ticket) 

https://user-images.githubusercontent.com/22355127/223253273-cb8628eb-e5c9-4ba9-8705-ef373ba8dd10.mov

be your changes

## Reference

VPN-3307 && VPN-4262

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2023-03-07 20:58 UTC, MattLichtenstein requested changes

2023-03-07 20:58 UTC, MattLichtenstein commented on src/apps/vpn/ui/screens/initialize/ViewInitialize.qml
>          ListModel {
Animations on slides 2, 3, and 4 are in the wrong order

2023-03-08 09:11 UTC, flodolo approved these changes

2023-03-08 15:11 UTC, MattLichtenstein approved these changes

2023-03-08 18:05 UTC, merged