ignore - mhop addition
mozilla-mobile/mozilla-vpn-client pull request #6247
Opened 2023-03-08 05:47 UTC by mozrokafor

## Description

    Describe your changes

## Reference

    i.e Jira or Github issue URL

2023-03-09 19:21 UTC, bakulf commented on tests/functional/testMultihop.js
> + const assert = require('assert');
why this extra space before each line? It makes almost impossible to review this PR. Can you please format this file correctly?

2023-04-03 19:54 UTC, birdsarah requested changes

2023-04-03 19:54 UTC, birdsarah commented on tests/functional/testMultihop.js
> +  this.ctx.authenticationNeeded = true;
Why is this duplicating the next two lines?

2023-04-03 19:54 UTC, birdsarah commented on tests/functional/testMultihop.js
> +  it.only('opening the entry and exit server list', async () => {
`it.only` means only this test will run in this test suite.

2023-04-03 19:54 UTC, birdsarah commented on tests/functional/testMultihop.js
> +  //  it.skip('Pick cities for entries', async () => {
why is this commented out? why not use `it.skip`?

2023-04-03 19:54 UTC, birdsarah commented on tests/functional/testMultihop.js
> +  // faulty on wasm -- fast follow to investigate
but it has been working? (if the tests are currently green then I don't understand why it's faulty on wasm)

2023-06-22 02:12 UTC, lesleyjanenorton commented
Closing for staleness. Feel free to reopen if there is further work to commit.

2023-06-22 02:12 UTC, closed without merging