add metric for excluded apps
mozilla-mobile/mozilla-vpn-client pull request #6305
Opened 2023-03-14 21:52 UTC by mcleinman

## Description

Adding session metric for count of excluded apps. Ping is sent in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6303.

Data review was [previously approved](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5702#pullrequestreview-1272682462).

Also improving glean categorization for a prior metric.

## Reference

https://mozilla-hub.atlassian.net/browse/VPN-4066

## Checklist
    
- [X] My code follows the style guidelines for this project
- [X] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [X] I have performed a self review of my own code
- [X] I have commented my code PARTICULARLY in hard to understand areas
- [X] I have added thorough tests where needed

2023-03-16 11:00 UTC, brizental commented on src/apps/vpn/apppermission.cpp
> +  QStringList applist = settingsHolder->vpnDisabledApps();
nit: This variable is unnecesary.

2023-03-16 11:02 UTC, brizental requested changes
Actually. Please add a unit test for this new colection.

2023-03-24 22:46 UTC, mcleinman commented on qtglean/metrics.yaml
> +settings:
Good call. I uplifted a separate PR that used the `settings` header to 2.15.0, so nothing will go live to production and then change.

2023-03-24 22:57 UTC, mcleinman commented
> Actually. Please add a unit test for this new colection.

A unit test of "record a metric glean, then check that it recorded it"? I believe we ran into some issues w/ trying to do better functional tests before, but can do something like this if you'd like.

2023-03-27 07:45 UTC, brizental commented
> A unit test of "record a metric glean, then check that it recorded it"? I believe we ran into some issues w/ trying to do better functional tests before, but can do something like this if you'd like.

I meant to add a unit test... I see the Controller doesn't have any, though. I have filed https://mozilla-hub.atlassian.net/browse/VPN-4445 to look into it. Please file a follow up for us to write tests for this collection, that is important. You can block it on the controller ticket I just filed and on https://mozilla-hub.atlassian.net/browse/VPN-4149. I'll make sure to prioritize VPN-4149 on the next sprint.

2023-03-27 07:46 UTC, brizental approved these changes

2023-03-27 16:27 UTC, mcleinman commented
> > A unit test of "record a metric glean, then check that it recorded it"? I believe we ran into some issues w/ trying to do better functional tests before, but can do something like this if you'd like.
> 
> I meant to add a unit test... I see the Controller doesn't have any, though. I have filed https://mozilla-hub.atlassian.net/browse/VPN-4445 to look into it. Please file a follow up for us to write tests for this collection, that is important. You can block it on the controller ticket I just filed and on https://mozilla-hub.atlassian.net/browse/VPN-4149. I'll make sure to prioritize VPN-4149 on the next sprint.

Ticket created: https://mozilla-hub.atlassian.net/browse/VPN-4452

2023-03-27 17:59 UTC, merged