VPN-3680: Update controller view strings
mozilla-mobile/mozilla-vpn-client pull request #6389
Opened 2023-03-21 03:49 UTC by lesleyjanenorton

## Description

- Adds new accessible label strings for the speed test and connection information/ip panel buttons
- Leaves old strings put for now and can be deleted when no longer needed in release branch

## Reference

VPN-3680

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2023-03-21 06:34 UTC, flodolo approved these changes

2023-03-21 06:34 UTC, flodolo commented on translations/strings.yaml
> +    comment: Accessible label for the button that opens the speed test view and initiates a speed test
Accessible or Accessibility?

2023-03-21 15:51 UTC, MattLichtenstein requested changes
Also, should we remove the old strings that are being replaced?

2023-03-21 15:51 UTC, MattLichtenstein commented on translations/strings.yaml
> -aboutUs:
probably need to add this back

2023-03-21 15:53 UTC, flodolo commented
> Leaves old strings put for now and can be deleted when no longer needed in release branch

This is not really necessary, automation takes care of keeping strings needed by release and release branches.

2023-03-23 16:58 UTC, lesleyjanenorton commented on translations/strings.yaml
> -aboutUs:
done, thanks!

2023-03-23 17:08 UTC, MattLichtenstein approved these changes

2023-03-24 07:43 UTC, merged