VPN-4429 Move Android-Glean into android/common
mozilla-mobile/mozilla-vpn-client pull request #6413
Opened 2023-03-22 17:01 UTC by strseb

## Description
Qt/Glean is now Shared Code, therefore the binds should live in android/common

2023-03-22 18:50 UTC, bakulf approved these changes

2023-03-22 18:50 UTC, bakulf commented on src/shared/platforms/android/androidcommons.cpp
> +        COMMON_UTILS_CLASS, "initializeGlean",
Great! The last remaining one seems to be `shareText`. Right?

2023-03-23 05:43 UTC, bakulf commented
File a Jira issue. Epic: relay app skeleton

2023-03-23 13:27 UTC, brizental requested changes
Still missing the removal of the Glean stuff from vpnClient/build.gradle :)

2023-03-27 16:27 UTC, brizental commented
Hey @strseb I think you missed this comment on my previous review?

> Still missing the removal of the Glean stuff from vpnClient/build.gradle :)

2023-03-27 16:58 UTC, brizental commented
Ha! You are right, duh! The only thing I think can go then is https://github.com/mozilla-mobile/mozilla-vpn-client/blob/abcc01b78359f081c8d33a90501de853beebb8c5/android/build.gradle#L148-L149.

2023-03-27 16:59 UTC, brizental approved these changes
r+wc

2023-03-28 12:23 UTC, merged