VPN-4476 Fix share logs
mozilla-mobile/mozilla-vpn-client pull request #6575
Opened 2023-04-04 13:38 UTC by strseb

## Description

    Describe your changes

## Reference

    i.e Jira or Github issue URL

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2023-04-04 14:10 UTC, bakulf approved these changes

2023-04-06 03:56 UTC, birdsarah approved these changes
Sorry did not mean to wipe baku's r+.

2023-04-06 04:07 UTC, bakulf approved these changes

2023-04-06 04:10 UTC, bakulf requested changes

2023-04-06 04:10 UTC, bakulf commented on src/shared/platforms/android/androidcommons.cpp
> +      UTILS_CLASS, "sharePlainText", "(Ljava/lang/String;)Z",
This is wrong. Shared plaintext should be in the shared android utils. Not in the VPN one. 

Can you move it there? And remove the UTILS macro on top.

2023-04-06 04:11 UTC, bakulf commented on src/shared/platforms/android/androidcommons.cpp
> +      UTILS_CLASS, "sharePlainText", "(Ljava/lang/String;)Z",
Also launch PlayStore should be in common utils.

2023-04-12 09:44 UTC, merged