VPN-891 - Replace individual email addresses with team
mozilla-mobile/mozilla-vpn-client pull request #6940
Opened 2023-05-19 02:10 UTC by birdsarah

Fixes VPN-891

Use vpn-telemetry@mozilla.com that folks can subscribe to and the whole org can look at if needed as opposed to individual email addresses.

2023-05-19 05:43 UTC, bakulf approved these changes

2023-05-19 07:19 UTC, brizental reviewed
Note: It's [suggested](https://mozilla.github.io/glean/book/reference/yaml/metrics.html#notification_emails) that there is always an individual's email on the `notification_emails` list alongside a team.

2023-05-21 23:22 UTC, birdsarah commented
> Note: It's [suggested](https://mozilla.github.io/glean/book/reference/yaml/metrics.html#notification_emails) that there is always an individual's email on the `notification_emails` list alongside a team.

Thanks @brizental. I've updated to match this.

2023-05-22 07:53 UTC, brizental requested changes

2023-05-22 07:53 UTC, brizental commented on docs/qtglean.md
> +      - brizental@mozilla.com, vpn-telemetry@mozilla.com
I don't think this is[ valid YAML list syntax](https://yaml.org/spec/1.2.2/#block-sequences). IIUC, this should be 
```suggestion
      - brizental@mozilla.com
      - vpn-telemetry@mozilla.com
```

2023-05-22 16:08 UTC, brizental approved these changes

2023-05-22 17:41 UTC, merged