VPN-4921 - Get all iOS logs to show up on console and log file
mozilla-mobile/mozilla-vpn-client pull request #7265
Opened 2023-06-20 13:52 UTC by brizental

I built this on top of #7256. Will rebase once that merged.

This PR starts at 59aa9126e12157fb9b7b4899c066007196b60e71.

2023-06-20 13:57 UTC, brizental commented on src/apps/vpn/platforms/ios/ioslogger.mm
> +}
nit: Make formatting consistent.

2023-06-20 13:58 UTC, brizental commented on src/apps/vpn/platforms/ios/ioscontroller.mm
>  void IOSController::cleanupBackendLogs() {
I noticed this was not getting called ever. I am not sure if that bug is related here, i should check it before merging. I think it's most likely a separate bug. I'll get back here with an answer.

2023-06-20 20:02 UTC, mcleinman reviewed
Couple small things. This is looking great, thank you.

2023-06-21 10:03 UTC, brizental commented on src/apps/vpn/platforms/ios/ioslogger.swift
> +        }
Fancy, I like it 💅

2023-06-21 10:03 UTC, brizental commented on src/apps/vpn/platforms/ios/ioslogger.swift
> +let WIREGUARD_LOGGER = IOSLoggerImpl(tag: "Wireguard")
The all caps is usual for global variables, which this one is. Is that convention different in Swift?

2023-06-21 10:04 UTC, brizental commented on src/apps/vpn/platforms/ios/iostunnelmanager.swift
> +                TunnelManager.logger.error(message: "Loading from preference failed: \(error)")
`logger` is a static variable and this is not a static function.

2023-06-22 18:23 UTC, mcleinman commented on src/apps/vpn/platforms/ios/iostunnelmanager.swift
> +                TunnelManager.logger.error(message: "Loading from preference failed: \(error)")
🤦🏻  Thanks

2023-06-22 18:25 UTC, mcleinman commented on src/apps/vpn/platforms/ios/ioslogger.swift
> +let WIREGUARD_LOGGER = IOSLoggerImpl(tag: "Wireguard")
Yes, it differs in Swift. From [Swift guidelines](https://www.swift.org/documentation/api-design-guidelines/):
`Names of types and protocols are UpperCamelCase. Everything else is lowerCamelCase.`

That said, I sometimes see globals/constants in upper camel case, but I've adjusted my suggestion above to lower camel case.

2023-06-22 18:36 UTC, mcleinman commented on src/apps/vpn/platforms/ios/ioslogger.swift
> +    private let dateFormatter = DateFormatter()
Nit: If you want to move the formatter setup out of the function, you could get fancy:
```suggestion
    private lazy var dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd.MM.yyyy HH:mm:ss"   
        return formatter
    }() = DateFormatter()
```

The snippet of setup code will be run the first time the `dateFormatter` is called, and never again. Unfortunately, as of now it needs to be done with a `var` and not `let`.

2023-06-23 08:12 UTC, brizental commented on src/apps/vpn/platforms/ios/ioscontroller.mm
>  void IOSController::cleanupBackendLogs() {
This is an unrelated bug. Filed https://mozilla-hub.atlassian.net/browse/VPN-5101

2023-06-23 22:42 UTC, mcleinman commented on src/apps/vpn/platforms/ios/ioslogger.swift
> +            dateFormatter.dateFormat = "dd.MM.yyyy HH:mm:ss"
```suggestion
```

With that new initializer, I believe we can delete this line.

2023-06-29 07:31 UTC, brizental commented on src/apps/vpn/platforms/ios/ioslogger.swift
> +                    logger.error(message: "Unable to create log file at \(appexLogFileURL)")
```suggestion
                    logger.error(message: "Unable to create log file at \(appexLogFileURL)")
                    return
```

2023-07-05 23:48 UTC, mcleinman requested changes
Code looks good, but it's not compiling for me or on TaskCluster. I think there are a couple things that were updated in one place but not another (causing an build issue), and a syntax problem. Let me know if you want any help with it.

2023-07-06 09:46 UTC, brizental commented
>  Code looks good, but it's not compiling for me or on TaskCluster. I think there are a couple things that were updated in one place but not another (causing an build issue), and a syntax problem. Let me know if you want any help with it.

Sorry for the bitrot here. This one kinda fell through the cracks 😳 Thanks for the patience, it should be working now!

2023-07-06 09:55 UTC, flodolo commented
Not sure what't happening with the addons being removed, but I assume this doesn't actually have strings to review?

2023-07-06 10:02 UTC, brizental commented
> Not sure what't happening with the addons being removed, but I assume this doesn't actually have strings to review?

Yeah I am so sorry. I made a little bit of a mess with the git history. Please ignore, trying to fix it now 👀

2023-07-06 18:44 UTC, mcleinman approved these changes
This is awesome, thank you! Tests great!

2023-07-07 09:01 UTC, merged