VPN-5545 - Remove all tutorial related code from tree
mozilla-mobile/mozilla-vpn-client pull request #8534
Opened 2023-11-10 13:43 UTC by brizental

Tutorials are not a supported feature since v2.17. We should be safe to remove all code related to it by now.

2023-11-13 13:41 UTC, strseb approved these changes
![r+](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/9611612/1aa32517-03cd-42b9-bec0-7cd48540bec4)

2023-11-13 15:10 UTC, MattLichtenstein commented
Removing the tutorials from the repo will eventually lead to them not being shipped to old version of the client. Do we want that? Not having tutorials on those old clients may have poor/unintended affects on the Tips and Tricks UI

2023-11-13 15:24 UTC, strseb commented
>Removing the tutorials from the repo will eventually lead to them not being shipped to old version of the client. Do we want that? Not having tutorials on those old clients may have poor/unintended affects on the Tips and Tricks UI. 

That would only affect people now installing "old" versions of the client, (right?) we cannot "unship" them for users who have them i thought 😅

2023-11-13 15:38 UTC, MattLichtenstein commented
> That would only affect people now installing "old" versions of the client, (right?) we cannot "unship" them for users who have them i thought 😅

Maybe we should double check, but I believe we remove addons from the system when they are no longer in the manifest

2023-11-13 15:44 UTC, MattLichtenstein commented
@strseb looks like we move unknown addons here https://github.com/mozilla-mobile/mozilla-vpn-client/blob/b2ea208aa49de20a67b272a06f4aeda3cf9381e0/src/addons/manager/addonmanager.cpp#L107-L126

2023-11-13 21:23 UTC, lesleyjanenorton requested changes
### ✨ 🧹🧹🧹 ✨
Very shiny!
While we are at it we should also remove:
- logo-error.svg
- logo-success.scvg
- logo-warning.svg

There is some cleanup we should do in `ExternalOpHandler` (maybe we no longer even need it? IIRC it was implemented to catch external operations that could interrupt a tutorial).

2023-11-13 21:27 UTC, lesleyjanenorton commented
> Removing the tutorials from the repo will eventually lead to them not being shipped to old version of the client. Do we want that? Not having tutorials on those old clients may have poor/unintended affects on the Tips and Tricks UI

@MattLichtenstein good point. Looping in @albionx. I'll add it to tomorrow's agenda.

2023-11-14 10:03 UTC, brizental commented on src/commands/commandui.cpp
> +#include "theme.h"
Great question, probably unnecessary 🤔

2023-11-14 10:28 UTC, brizental commented
> There is some cleanup we should do in ExternalOpHandler (maybe we no longer even need it? IIRC it was implemented to catch external operations that could interrupt a tutorial).

This is correct, the only registered blocker for the external op handler was tutorials. That is not gone on: [9bed839](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8534/commits/9bed8399861ed71ba950ca7f59f4d4c912daba9e)

2023-11-14 10:29 UTC, brizental commented on src/commands/commandui.cpp
> +#include "theme.h"
```suggestion
```

2023-11-15 03:32 UTC, lesleyjanenorton approved these changes
Nice, thank you!

2023-11-15 15:48 UTC, albionx commented
Provided we can't avoid that older clients lose the tutorials, I think we should wait before merging this in. I just checked on Looker and ~43% of clients are on versions 2.16 and below. Maybe we revisit in Mid/Late Dec, once 2.19 is out?

2023-11-15 15:49 UTC, brizental commented
> Provided we can't avoid that older clients lose the tutorials, I think we should wait before merging this in. I just checked on Looker and ~43% of clients are on versions 2.16 and below. Maybe we revisit in Mid/Late Dec, once 2.19 is out?

I will just leave the addons manifests in there. I'll go ahead with the removal of the code. cc @lesleyjanenorton

2023-11-15 17:36 UTC, merged