Android-WIP: Use our own activity && Roll our own BackBtn Handling
mozilla-mobile/mozilla-vpn-client pull request #862
Opened 2021-04-16 12:44 UTC by strseb

The Problem with #622 is that qt tries to turn itself down and failing to do so. So instead let's not have qt handle the back button as we're already doing this 90% of the times and just but the app in the background stack -> pausing it like if the home button was pressed. 

Waiting for confirmation if this works as i have no such device to reproduce :( - closes #622

2021-04-19 16:49 UTC, bakulf requested changes

2021-04-19 16:49 UTC, bakulf commented on src/mozillavpn.cpp
> +  // Register natvies of the vpn activity
natives?

2021-04-19 16:49 UTC, bakulf commented on src/platforms/android/androidvpnactivity.h
> +#ifndef ANDROIDVPNACTIVITY_H
header

2021-04-20 15:13 UTC, strseb commented
Marking no longer WIP: 
I was able to test this on a Remote huawei device - pressing back button now puts the app into a sleep state instead of trying to exit.

2021-04-21 11:02 UTC, bakulf approved these changes

2021-04-21 11:02 UTC, merged