VPN-6129 - Create daemon-specific metrics
mozilla-mobile/mozilla-vpn-client pull request #9013
Opened 2024-01-24 03:36 UTC by mcleinman

## Description

The connection health metrics all have a ping lifetime. However, in [this PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7124/) they were added to the daemon ping - and previously, two of them were already on both `main` and `session` pings. Thus, they're being misreported - for example, we increment one metric (`connection_health_stable_count`) for both Android daemon and app session health checks - and clear it whenever either ping is sent.

This PR adds new variables for the daemon, and removes the existing metrics from `main` and `daemon` pings.

## Reference

https://mozilla-hub.atlassian.net/browse/VPN-6129

## Checklist
    
- [x] My code follows the style guidelines for this project
- [x] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [x] I have performed a self review of my own code
- [x] I have commented my code PARTICULARLY in hard to understand areas
- [x] I have added thorough tests where needed

2024-01-24 03:38 UTC, mcleinman commented
This needs a data steward review. However, I want to make sure this approach is agreed upon before requesting that review. Thus, keeping this on draft for now.

@brizental , despite being on draft, please review - I want to make sure this approach makes sense.

2024-01-24 08:45 UTC, brizental commented
> and clear it whenever either ping is sent.

This is incorrect. Even though the metric is lifetime ping, there are different instances of each metric per ping so that they are cleared based on the lifetime of each ping separately. I am not sure what is being misreported about these metrics, but I am skeptical that this would fix it.

2024-01-24 08:47 UTC, brizental requested changes

2024-01-24 08:47 UTC, brizental commented on src/telemetry/metrics.yaml
> +  daemon_conn_health_no_signal:
Creating these new metrics would have the same effect as sending the same metric is multiple pings, it just makes the metric design a bit repetitive.

2024-01-29 22:52 UTC, mcleinman commented
Thanks. Closing this, pending more investigation.

2024-01-29 22:52 UTC, closed without merging