Lower C++ language version to C++14
mozilla-mobile/mozilla-vpn-client pull request #973
Opened 2021-05-05 19:08 UTC by abpostelnicu

As per #955, in order to be able to build on platforms that don't have fully support for C++17, C++14 should be considered the minimum required.

2021-05-06 10:18 UTC, bakulf requested changes
This breaks wasm. Can you investigate why? We can also have 2 different compiler versions, one for the builds, and one for wasm.

2021-05-06 10:32 UTC, abpostelnicu commented
@bakulf do you think this is related with my change, I see this warning that is transformed into an error:
```
In file included from /opt/5.15.0/wasm_32/include/QtNetwork/QNetworkReply:1:
266
In file included from /opt/5.15.0/wasm_32/include/QtNetwork/qnetworkreply.h:44:
267
In file included from /opt/5.15.0/wasm_32/include/QtCore/QIODevice:1:
268
In file included from /opt/5.15.0/wasm_32/include/QtCore/qiodevice.h:45:
269
In file included from /opt/5.15.0/wasm_32/include/QtCore/qobject.h:47:
270
/opt/5.15.0/wasm_32/include/QtCore/qstring.h:1229:22: warning: definition of implicit copy constructor for 'QCharRef' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
271
    inline QCharRef &operator=(const QCharRef &c) { return operator=(QChar(c)); }
```

2021-05-06 16:35 UTC, bakulf commented
So, no, those are not your errors and I still don't understand why changing the clang creates an issue with wasm (which doesn't use clang!). The issue seems to be in how we treat warning with C++14. Can you please try the following changes:

1. in test/unit/unit.pro add:
```
wasm {
    CONFIG += c++1z
   QMAKE_CXXFLAGS *= -Werror
}
```

2021-05-06 17:14 UTC, abpostelnicu commented
> So, no, those are not your errors and I still don't understand why changing the clang creates an issue with wasm (which doesn't use clang!). The issue seems to be in how we treat warning with C++14. Can you please try the following changes:
> 
> 1. in test/unit/unit.pro add:
> 
> ```
> wasm {
>     CONFIG += c++1z
>    QMAKE_CXXFLAGS *= -Werror
> }
> ```

We could just remove the warning that causes issues Wno-…

2021-05-07 12:30 UTC, bakulf approved these changes

2021-05-07 12:30 UTC, merged