DRAFT: taskcluster check
mozilla-mobile/mozilla-vpn-client pull request #9964
Opened 2024-10-15 22:52 UTC by mcleinman

# Bug only replicates on taskcluster, so this is to build there - not a real PR
---
## Description

    Describe your changes

## Reference

    i.e Jira or Github issue URL

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

2024-10-24 18:46 UTC, oskirby requested changes
I don't like this fix, it feels very brittle and it fills me with concern over what exactly is allowed to be input as a valid string ID. I would prefer that we change the `servers.Malmö` ID to just `servers.Malmo` and rely on the translations to turn that into `Malmö` as appropriate.

If it's just one city translation to deal with, it shouldn't be that hard to copy the files over in Pontoon as necessary. Or there more to it than just changing the string ID in the VPN app (eg: does the ID come from guardian or something?).

2024-10-24 22:22 UTC, mcleinman commented
> I don't like this fix, it feels very brittle and it fills me with concern over what exactly is allowed to be input as a valid string ID. I would prefer that we change the `servers.Malmö` ID to just `servers.Malmo` and rely on the translations to turn that into `Malmö` as appropriate.
> 
> If it's just one city translation to deal with, it shouldn't be that hard to copy the files over in Pontoon as necessary. Or there more to it than just changing the string ID in the VPN app (eg: does the ID come from guardian or something?).

I agree that it's waaaay too brittle.

The ID comes from the English name of the city. So we'd have to change the name of the city in the app to use `servers.Malmo`. 

Alternatively, we could strip special characters before sending it out to be translated, so the translation string is `servers.Malm`. (Currently it's `servers.Malmö` and we strip out that special o when ingesting it back into the app, after it's been translated.) In this case, we'd still need to work w/ l10n team to copy over the translations from `servers.Malmö` to `servers.Malm`. 

How does that sound? In my mind, it's a bit more generalizable (it should work for any future cities with a special character), though it would take work w/ the translations team. If this sounds like an okay approach to you, let me know and I'll close this PR in favor of a new one.

2024-10-28 15:23 UTC, oskirby commented
> > I don't like this fix, it feels very brittle and it fills me with concern over what exactly is allowed to be input as a valid string ID. I would prefer that we change the `servers.Malmö` ID to just `servers.Malmo` and rely on the translations to turn that into `Malmö` as appropriate.
> > If it's just one city translation to deal with, it shouldn't be that hard to copy the files over in Pontoon as necessary. Or there more to it than just changing the string ID in the VPN app (eg: does the ID come from guardian or something?).
> 
> I agree that it's waaaay too brittle.
> 
> The ID comes from the English name of the city. So we'd have to change the name of the city in the app to use `servers.Malmo`.
> 
> Alternatively, we could strip special characters before sending it out to be translated, so the translation string is `servers.Malm`. (Currently it's `servers.Malmö` and we strip out that special o when ingesting it back into the app, after it's been translated.) In this case, we'd still need to work w/ l10n team to copy over the translations from `servers.Malmö` to `servers.Malm`.
> 
> How does that sound? In my mind, it's a bit more generalizable (it should work for any future cities with a special character), though it would take work w/ the translations team. If this sounds like an okay approach to you, let me know and I'll close this PR in favor of a new one.

I am in favor of changing the city ID to `servers.Malmo` and we will just have to work with the translation team to copy the names over. If we simply drop the non-ASCII chars then it might lead to even more confusing IDs for other cities in the future.

We probably also want to enforce some kind of lint to ensure that the IDs only contain ASCII characters or something to prevent this from happening again in the future.

2024-10-29 14:45 UTC, mcleinman commented
> I am in favor of changing the city ID to `servers.Malmo` and we will just have to work with the translation team to copy the names over. If we simply drop the non-ASCII chars (eg: `servers.Malm`) then it might lead to even more confusing IDs for other cities in the future.
> 
> We probably also want to enforce some kind of lint to ensure that the IDs only contain ASCII characters or something to prevent this from happening again in the future.

The city ID is a derivative of the English city name, which in turn comes directly from Mullvad. So we can't change the city ID to `servers.Malmo` without some gross custom hacky code (either when coming back from Mullvad API or when creating the server translation strings). (I'm reluctant to do a general solution like "convert special vowels to regular vowels" - this current bug is because TaskCluster apparently handles some special characters differently than my machine, and I want to remove as much ambiguity as possible as to what a "special character" is, and use a fairly broad definition.)

We already use a parsed city string ID of `servers.Malm` internally when running the app - we strip out the ö when processing the strings to bring into the actual app. (However, we don't do this before sending the string out for translation.) 

Potential steps forward, since we're both agreed this is hacky:
1) Write hacky code to change the string ID before sending it out for translation. This will be similarly hacky, but live elsewhere - `update_server_names.py` (for preparing strings to send to the server) and in  `Localizer::getTranslatedCityName` (so when looking for `Malmö` we actually search for `Malmo`).
2) Write hacky code to change the actual string that the Mullvad API returns to us, to not use the ö - which will allow for a `servers.Malmo` string ID. This has a major downside of changing what we actually show users in the app for this scity's name.
3) Keep digging in to the inner workings of lconvert. (In my initial research, once I got to "something is happening in `lconvert` that we can't see/understand, I stopped investigating.) I looked at the lconvert documentation and searched the internet for a bit, and couldn't account for anything that would cause the different behavior between my machine and TaskCluster. But I'm not personally satisfied that I can't confidently say exactly why this is happening. I stopped my research because it didn't feel worthwhile to spend another half day or day on research for a bug of this magnitude, but could very happily dive back in.
4) Other options I'm not considering?
5) Merge this PR

My inclination is #1 or #4 (if you have other ideas), but I'm genuinely open to any of these paths.

2024-11-12 23:56 UTC, mcleinman commented
Closing in favor of https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10029

2024-11-12 23:56 UTC, closed without merging